const medicalStaticData = [
  {
    employeeId: '1245',
    name: 'Harry J Potter',
    bloodType: 'A+',
    allergies: 'Peanuts',
    doctor: 'Dr. James Smith',
    condition: 'Asthma',
    doctorPhone: '123-456-7890',
    doctorAddress: '123 Main St',
    doctorCity: 'London',
    doctorState: 'England',
    doctorZip: '12345',
    hepB1: '2022-01-10',
    hepB2: '2022-02-10',
    hepB3: '2022-03-10',
    hepBDeclined: false,
    medicalConditions: 'Asthma',
    medications: 'Inhaler',
  },
  {
    employeeId: '1246',
    name: 'Severus Snape',
    bloodType: 'B-',
    allergies: '',
    doctor: 'Dr. Sarah Lee',
    condition: '',
    doctorPhone: '',
    doctorAddress: '',
    doctorCity: '',
    doctorState: '',
    doctorZip: '',
    hepB1: '',
    hepB2: '',
    hepB3: '',
    hepBDeclined: true,
    medicalConditions: '',
    medications: '',
  },
  {
    employeeId: '1247',
    name: 'Tom M. Riddle',
    bloodType: 'O+',
    allergies: 'None',
    doctor: 'Dr. Michael Brown',
    condition: 'Diabetes',
    doctorPhone: '555-555-5555',
    doctorAddress: '456 Elm St',
    doctorCity: 'Manchester',
    doctorState: 'England',
    doctorZip: '54321',
    hepB1: '2021-05-01',
    hepB2: '2021-06-01',
    hepB3: '2021-07-01',
    hepBDeclined: false,
    medicalConditions: 'Diabetes',
    medications: 'Insulin',
  },
  {
    employeeId: '1248',
    name: 'Lily Evans',
    bloodType: 'AB-',
    allergies: 'Penicillin',
    doctor: 'Dr. Steve White',
    condition: '',
    doctorPhone: '',
    doctorAddress: '',
    doctorCity: '',
    doctorState: '',
    doctorZip: '',
    hepB1: '',
    hepB2: '',
    hepB3: '',
    hepBDeclined: false,
    medicalConditions: '',
    medications: '',
  },
  {
    employeeId: '1249',
    name: 'Sirius Black',
    bloodType: 'O-',
    allergies: '',
    doctor: 'Dr. Jennifer Grey',
    condition: '',
    doctorPhone: '',
    doctorAddress: '',
    doctorCity: '',
    doctorState: '',
    doctorZip: '',
    hepB1: '',
    hepB2: '',
    hepB3: '',
    hepBDeclined: false,
    medicalConditions: '',
    medications: '',
  },
  {
    employeeId: '1250',
    name: 'Remus Lupin',
    bloodType: 'B+',
    allergies: 'Dust',
    doctor: 'Dr. Robert Black',
    condition: 'Allergy',
    doctorPhone: '222-333-4444',
    doctorAddress: '789 Oak St',
    doctorCity: 'Bristol',
    doctorState: 'England',
    doctorZip: '67890',
    hepB1: '',
    hepB2: '',
    hepB3: '',
    hepBDeclined: false,
    medicalConditions: 'Allergy',
    medications: 'Antihistamine',
  }
];

export default medicalStaticData;
