import Photo from '../../../assets/officer-photo.jpg';

const employeeList = [
    {
        id: 'E001',
        name: 'Michael J. Rodriguez',
        rank: 'Detective Sergeant',
        division: 'Criminal Investigation Division',
        status: 'Active',
        photo: Photo,
        badgeId: 'PD-2025-2365',
        website: 'https://michael-rodriguez.com',
        personalInfo: {
            ssn: '9653 6666 2626',
            address: '31, Baker Street, Philadelphia, New Jersey, 23125',
            dob: '1986-10-12',
            pob: 'New York',
            phone: '(555) 123-4567',
            middleName: 'John',
            lastName: 'Rodriguez',
            firstName: 'Michael',
            gender: 'Male',
            maritalStatus: 'Married',
            email: 'michael.rodriguez@email.com',
            nationality: 'American',
            state: 'New Jersey',
            city: 'Philadelphia',
            zipCode: '23125',
        },
        employmentDetails: {
            hourlyRate: '22 $',
            hireDate: '2002-10-26',
            promotionDate: '2010-05-15',
            endDate: '',
            socialSecurity: '9653 6666 2626',
            badgeNumber: 'PD-2025-2365',
            position: 'Detective Sergeant',
            department: 'Criminal Investigation Division',
        },
        contactInfo: {
            phone: '(555) 123-4567',
            pager: '(555) 123-4567',
            cellPhone: '(555) 123-4567',
            spouseName: 'Cinderella',
            spouseContact: '222 152 2252',
            address: '31, Baker Street, Philadelphia, New Jersey, 23125',
            email: 'michael.rodriguez@email.com',
            emergencyContact: {
                name: 'Cinderella',
                phone: '222 152 2252',
                address: 'White House',
                altPhone: '111 222 3333',
            },
            employerContact: {
                primary: '222 152 2252',
                secondary: '555 555 5555',
            },
        },
        otherDetails: {
            driverLicense: 'D1234567',
            expirationDate: '2025-12-31',
            primaryDependent: {
                name: 'Ella Rodriguez',
                phone: '333 444 5555',
                school: 'White House School',
                dob: '2006-10-12',
            },
            secondaryDependent: {
                name: 'Sam Rodriguez',
                phone: '444 555 6666',
                school: 'White House School',
                dob: '2008-11-15',
            },
        },
    },
    {
        id: 'E002',
        name: 'Sarah A. Johnson',
        rank: 'Police Officer',
        division: 'Patrol Division',
        status: 'Inactive',
        photo: Photo,
        badgeId: 'PD-2025-2366',
        website: '',
        personalInfo: {
            ssn: '1234 5678 9101',
            address: '45, Elm Street, Springfield, Illinois, 62704',
            dob: '1990-03-05',
            pob: 'Chicago',
            phone: '(555) 987-6543',
            middleName: 'Ann',
            lastName: 'Johnson',
            firstName: 'Sarah',
            gender: 'Female',
            maritalStatus: 'Single',
            email: 'sarah.johnson@email.com',
            nationality: 'American',
            state: 'Illinois',
            city: 'Springfield',
            zipCode: '62704',
        },
        employmentDetails: {
            hourlyRate: '18 $',
            hireDate: '2012-06-01',
            promotionDate: '',
            endDate: '',
            socialSecurity: '1234 5678 9101',
            badgeNumber: 'PD-2025-2366',
            position: 'Police Officer',
            department: 'Patrol Division',
        },
        contactInfo: {
            phone: '(555) 987-6543',
            pager: '(555) 987-6543',
            cellPhone: '(555) 987-6543',
            spouseName: '',
            spouseContact: '',
            address: '45, Elm Street, Springfield, Illinois, 62704',
            email: 'sarah.johnson@email.com',
            emergencyContact: {
                name: 'Anna Johnson',
                phone: '555 111 2222',
                address: 'Springfield',
                altPhone: '',
            },
            employerContact: {
                primary: '555 111 2222',
                secondary: '',
            },
        },
        otherDetails: {
            driverLicense: 'J2345678',
            expirationDate: '2024-08-15',
            primaryDependent: {
                name: '',
                phone: '',
                school: '',
                dob: '',
            },
            secondaryDependent: {
                name: '',
                phone: '',
                school: '',
                dob: '',
            },
        },
    },
    {
        id: 'E003',
        name: 'James M. Smith',
        rank: 'Chief',
        division: 'Administration Division',
        status: 'Active',
        photo: Photo,
        badgeId: 'PD-2025-2367',
        website: 'https://jamesmsmith.org',
        personalInfo: {
            ssn: '9876 5432 1098',
            address: '78, Maple Avenue, Boston, Massachusetts, 02118',
            dob: '1975-07-20',
            pob: 'Boston',
            phone: '(555) 555-5555',
            middleName: 'Matthew',
            lastName: 'Smith',
            firstName: 'James',
            gender: 'Male',
            maritalStatus: 'Married',
            email: 'james.smith@email.com',
            nationality: 'American',
            state: 'Massachusetts',
            city: 'Boston',
            zipCode: '02118',
        },
        employmentDetails: {
            hourlyRate: '30 $',
            hireDate: '1998-01-15',
            promotionDate: '2005-09-10',
            endDate: '',
            socialSecurity: '9876 5432 1098',
            badgeNumber: 'PD-2025-2367',
            position: 'Chief',
            department: 'Administration Division',
        },
        contactInfo: {
            phone: '(555) 555-5555',
            pager: '(555) 555-5555',
            cellPhone: '(555) 555-5555',
            spouseName: 'Linda Smith',
            spouseContact: '555 666 7777',
            address: '78, Maple Avenue, Boston, Massachusetts, 02118',
            email: 'james.smith@email.com',
            emergencyContact: {
                name: 'Linda Smith',
                phone: '555 666 7777',
                address: 'Boston',
                altPhone: '555 888 9999',
            },
            employerContact: {
                primary: '555 666 7777',
                secondary: '555 888 9999',
            },
        },
        otherDetails: {
            driverLicense: 'S3456789',
            expirationDate: '2026-03-20',
            primaryDependent: {
                name: 'Tom Smith',
                phone: '555 777 8888',
                school: 'Boston High',
                dob: '2002-04-10',
            },
            secondaryDependent: {
                name: 'Lucy Smith',
                phone: '555 999 0000',
                school: 'Boston High',
                dob: '2004-06-15',
            },
        },
    },
];

export default employeeList;
